### ISSUE TITLE
Sentry version > 6 not supported

### ISSUE THREAD

**Issue by joggeli34** [quarkiverse/quarkus-logging-sentry#59]
When using the sentry library (6.1.4), the application failes to start with following error:

```
ERROR: Failed to start application (with profile prod)
java.lang.NoSuchMethodError: 'void io.sentry.SentryOptions.setDebug(java.lang.Boolean)'
	at io.quarkus.logging.sentry.SentryHandlerValueFactory.toSentryOptions(SentryHandlerValueFactory.java:59)
	at io.quarkus.logging.sentry.SentryHandlerValueFactory.create(SentryHandlerValueFactory.java:28)
	at io.quarkus.deployment.steps.SentryProcessor$addSentryLogHandler1613402751.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.SentryProcessor$addSentryLogHandler1613402751.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:60)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
```

**Comment by ia3andy** [comment]
The Sentry version should be managed by the extension. I see there is a dependabot update to 6, I will see into providing a new release.

**Comment by ia3andy** [comment]
As soon as 1.2.0 is out on Maven Central, let me know if it fixes the bug..

**Comment by joggeli34** [comment]
Thanks for the fast answer and release. I checked it, it now starts and works correctly for us.
